# va contenir les github actions // le pipeline

# Nom de pipeline
name: Build & Deploy Spring app

# when to trigger this pipeline
on:
  # Ici, le pipeline s'exécute automatiquement à chaque push de
  # code sur le dépôt Git.
  push:
    branches:
      - main

# set of steps each job is whole process in separate machine
jobs:
  # name of the job build-deploy
  build-deploy:
    name: Build and Deploy Spring Boot for beginner
    # la machine sur laquelle ce job va être exécuté
    runs-on: ubuntu-latest
    steps:
      # après l'exécution de cette étape, le code de votre dépôt Git sera cloné dans la machine virtuelle (ubuntu-latest) où le job s'exécute
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        # comme des paramètres
        with:
          # Ce paramètre spécifie quelle distribution de JDK vous voulez installer
          distribution: 'corretto'
          java-version: 17

      # Exécution des tests unitaires
      - name: Unit Tests
        # manual script
        run: mvn -B test --file pom.xml

      # Compilation de l'application
      - name: Build the application
        # multiple commandes
        run: |
          mvn clean
          mvn -B package --file pom.xml
