# va contenir les github actions // le pipeline

# Nom de pipeline
name: Build & Deploy Spring app
# when to trigger this pipeline
on:
  # Ici, le pipeline s'exécute automatiquement à chaque push de
  # code sur le dépôt Git.
  push:
    branches:
      - main
jobs:
  # name of the job build-deploy
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          # Ce paramètre spécifie quelle distribution de JDK vous voulez installer
          distribution: 'corretto'
          java-version: 17
      # Exécution des tests unitaires
      - name: Unit Tests
        # manual script
        run: mvn -B test --file pom.xml
      # Compilation de l'application
      - name: Build the application
        # multiple commandes
        run: |
          mvn clean
          mvn -B package --file pom.xml

